---
title: "STATS230 Homework #3"
author: "John Corrette"
date: "2/7/2022"
output: html_document
vignette: >
  %\VignetteIndexEntry{STATS230_John_Corrette_HW_3}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bench)
library(ggplot2)
library(tidyr)
library(matlib)
is_available <- require(stats230.Rpackage)
if (!is_available) {
  library(devtools)
  install_github("jcorrett/stats230.Rpackage")
}
library(stats230.Rpackage) 
```

## Problem 1

```{r Read Heart Data, warning=FALSE}
data <- read.table("http://www-stat.stanford.edu/~tibs/ElemStatLearn/datasets/SAheart.data",
	sep=",",head=T,row.names=1)
DF <- data.frame(data)
X <- apply(as.matrix.noquote(DF),2,as.numeric)
ystr <- "chd"
xstr <- c("sbp","tobacco","ldl","adiposity","typea","obesity","alcohol","age")
#xstr <- c("ldl","age")
y <- X[, ystr]
X <- X[, xstr]
X <- scale(X) #standardize to have 0 mean columns w/ var = 1
alpha <- 1e-3
tol <- 1e-10

gd_df <- gd_logistic_regression(X,y,alpha,tol)
gd_beta <- gd_df[[1]]
gd_llhood <- gd_df[[2]]
gd_beta_CI <- gd_df[[3]]

nr_df <- nr_logistic_regression(X,y,tol)
nr_beta <- nr_df[[1]]
nr_llhood <- nr_df[[2]]
nr_beta_CI <- nr_df[[3]]

plot(gd_llhood)

plot(nr_llhood)

mylogit <- glm.fit(X,y,family=binomial(),intercept = FALSE)
gd_beta
gd_beta_CI
nr_beta
nr_beta_CI
```

## Problem 2

```{r EM Blood}
p <- c(0.1,0.3,0.6) #(pA,pB,pO)
n <- c(6,55,4,35) #(nA,nB,nAB,nO)
tol <- 1e-16
blood_data <- em_blood(n,p,tol)
blood_data[[1]] #(pA,pB,pO)
blood_data[[2]] #(pAA,pAO,pBB,pBO,pAB,pOO)
```

## Problem 3

```{r HMM Sim}
set.seed(230)#set "random" seed for curated example
P <- rbind(c(0.98,0.02),c(0.05,0.95))
E <- rbind(c(1/6,1/6,1/6,1/6,1/6,1/6),
           c(1/10,1/10,1/2,1/10,1/10,1/10))
v <- c(1/2,1/2)

sim_data <- sim_HMM(P,E,v,400)
x <- sim_data[[1]]
y <- sim_data[[2]]
plot(x)
plot(y)
```
```{r Forward/Backward Algorithms}
f_data <- forward_HMM(P,E,v,y,length(v))
b_data <- backward_HMM(P,E,v,y,length(v))
a <- f_data[[2]]
b <- b_data[[2]]

p_x <- a*b/colSums(a*b,2)
plot(x-1,col="black")
lines(p_x[1,],type = "l",col="blue")
lines(p_x[2,],type = "l",col = "red")
```
```{r Baum-Welch Algorithm}
eps <- 0.1*runif(2)

P_guess <- rbind(c(1-eps[1],eps[1]),c(eps[2],1-eps[2]))
E_guess <- matrix(1/6,nrow=2,ncol=6)
v_guess <- c(0.5,0.5)
bw_data <- bw_HMM(P_guess,E_guess,v_guess,y,2,6,1e-14)
P_est <- bw_data[[1]]
E_est <- bw_data[[2]]
v_est <- bw_data[[3]]
P_est
E_est
v_est
```
```{r Baum-Welch Algorithm}
eps <- 0.1*runif(2)

P_guess <- rbind(c(1-eps[1],eps[1]),c(eps[2],1-eps[2]))
E_guess <- matrix(1/6,nrow=2,ncol=6)
v_guess <- c(0.5,0.5)
bw_data <- bw_HMM(P_guess,E_guess,v_guess,y,2,6,1e-14)
P_est <- bw_data[[1]]
E_est <- bw_data[[2]]
v_est <- bw_data[[3]]
P_est
E_est
v_est
```

```{r Baum-Welch Algorithm}
P_guess <- P
E_guess <- E
v_guess <- v
bw_data <- bw_HMM(P_guess,E_guess,v_guess,y,2,6,1e-14)
P_est <- bw_data[[1]]
E_est <- bw_data[[2]]
v_est <- bw_data[[3]]
P_est
E_est
v_est
```
