---
title: "STATS230 Homework #2"
author: "John Corrette"
date: "1/14/2022"
output: html_document
vignette: >
  %\VignetteIndexEntry{STATS230_John_Corrette_HW_1}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bench)
library(ggplot2)
library(tidyr)
is_available <- require(stats230.Rpackage)
if (!is_available) {
  library(devtools)
  install_github("jcorrett/stats230.Rpackage")
}
library(stats230.Rpackage) 
```

```{r MVN test}
mu <- c(1,1,1,1)
Sigma <- rbind(c(1,0.05,0.05,0.05),c(0.05,1,0.05,0.05),c(0.05,0.05,1,0.05),c(0.05,0.05,0.05,1))
N <- 100

x <- rand_MVN(mu,Sigma,N)
mu_hat <- rowMeans(x)
Sigma_hat <- cov(t(x))
mu_hat
Sigma_hat
```

```{r OLS}
data <- read.csv(file = 'C:/Users/Jack Corrette/Desktop/Statistical_Computing_Methods/homework2_regression.csv')
data <- as.matrix(data)
y <- data[,1]
#X <- data[,-1]
X <- cbind(data[,2],data[,6])

beta_QR <- OLS_QR(X,y)
y_hat_QR <- X%*%beta_QR
beta_SVD <- OLS_SVD(X,y)
y_hat_SVD <- X%*%beta_SVD
plot(X[,2],y)
points(X[,2],y_hat_QR,col="blue")
points(X[,2],y_hat_SVD,col="red")
```
